# Generate Ansible group_vars from Terraform variables
# Creates YAML files for Ansible groups with K8s and GitHub runner configuration

resource "local_file" "k8s_all_groupvars" {
  filename = "${path.module}/../ansible/group_vars/k8s_all.yml"

  content = <<-EOT
# Kubernetes cluster shared configuration - Generated by Terraform
# DO NOT EDIT MANUALLY

---
# Kubernetes version and network configuration
k8s_version: "${var.k8s_version}"
k8s_pod_cidr: "${var.k8s_pod_cidr}"

# Container runtime configuration
cri_socket: "unix:///var/run/crio/crio.sock"
crio_version: "${var.crio_version}"

# Proxy settings (applied to all cluster nodes)
http_proxy: "${var.http_proxy}"
https_proxy: "${var.https_proxy}"
no_proxy: "${var.no_proxy}"

# System timezone
timezone: "Europe/Zurich"

# Calico CNI configuration
calico_version: "${var.calico_version}"

# Flannel alternative (if using Flannel instead of Calico)
flannel_version: "v0.22.3"

# Kubelet configuration
kubelet_config:
  max-pods: 250
  log-level: 2
EOT

  depends_on = []
}

resource "local_file" "k8s_masters_groupvars" {
  filename = "${path.module}/../ansible/group_vars/k8s_masters.yml"

  content = <<-EOT
# Kubernetes master nodes configuration - Generated by Terraform
# DO NOT EDIT MANUALLY

---
# Master node specific settings
node_labels:
  node-role.kubernetes.io/master: ""

# kubeadm init settings
kubeadm_config:
  apiVersion: kubeadm.k8s.io/v1beta3
  kind: ClusterConfiguration
  kubernetesVersion: "v${k8s_version}"
  controlPlaneEndpoint: ""  # Set to load balancer IP in production
  networking:
    podSubnet: "${var.k8s_pod_cidr}"
    dnsDomain: cluster.local
  apiServer:
    extraArgs:
      - audit-log-maxage: "30"
  controllerManager:
    extraArgs:
      - node-monitor-grace-period: "20s"
EOT

  depends_on = []
}

resource "local_file" "k8s_workers_groupvars" {
  filename = "${path.module}/../ansible/group_vars/k8s_workers.yml"

  content = <<-EOT
# Kubernetes worker nodes configuration - Generated by Terraform
# DO NOT EDIT MANUALLY

---
# Worker node specific settings
node_labels:
  node-role.kubernetes.io/worker: ""

# kubeadm join settings (specific values set at runtime from master)
kubeadm_config:
  apiVersion: kubeadm.k8s.io/v1beta3
  kind: JoinConfiguration
  discovery:
    bootstrapToken:
      apiServerEndpoint: ""  # Set at runtime from master
      token: ""              # Set at runtime from master
      caCertHash: ""         # Set at runtime from master
EOT

  depends_on = []
}

resource "local_file" "github_runners_groupvars" {
  filename = "${path.module}/../ansible/group_vars/github_runners.yml"

  content = <<-EOT
# GitHub Actions Runner configuration - Generated by Terraform
# DO NOT EDIT MANUALLY

---
# GitHub runner setup
github_org: "${var.github_runner_org}"
github_runner_version: "${var.github_runner_version}"
github_runner_user: "github-runner"
github_runner_home: "/home/github-runner"
github_runner_group: "default"  # Will be overridden per environment

# Runner registration details
runner_registration_timeout: 300

# Service configuration
runner_service_name: "github-actions.runner"
runner_service_description: "GitHub Actions self-hosted runner"

# .NET dependencies for runner
install_dotnet_deps: true
EOT

  depends_on = []
}

output "ansible_groupvars_files" {
  value = {
    k8s_all    = local_file.k8s_all_groupvars.filename
    k8s_masters = local_file.k8s_masters_groupvars.filename
    k8s_workers = local_file.k8s_workers_groupvars.filename
    github_runners = local_file.github_runners_groupvars.filename
  }
  description = "Paths to generated Ansible group_vars files"
}

