name: Deploy to Kubernetes
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: "development"
        type: choice
        options:
          - development
          - production
      chart:
        description: 'Deploy Component'
        required: true
        default: "*"
        type: choice
        options:
          - "*"
          - calico
          - cert-manager
          - ci-access
          - cloudflare
          - grafana
          - metallb
          - persistent-volumes
          - production
          - prometheus
          - sealed-secrets
          - traefik
jobs:
  call-deploy:
    runs-on: 
      group: ${{ format('lithium-{0}', github.event.inputs.environment) }}
      
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup Helm
      uses: azure/setup-helm@v4
    
    - name: Extract branch
      shell: bash
      run: echo "revision=$( echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | sed 's/\//-/g')" >> $GITHUB_OUTPUT
      id: branch
        
    - name: Deploy the Helm chart(s)
      run: | 
        CHART_NAME=${{ github.event.inputs.chart }}
        ENVIRONMENT=${{ github.event.inputs.environment }}
        
        if [[ "$CHART_NAME" == "*" ]]; then
          CHART_PATHS=$(find ./cicd -mindepth 1 -maxdepth 1 -type d)
        else
          CHART_PATHS="./cicd/$CHART_NAME"
        fi

        for path in $CHART_PATHS; do
          echo "Deploying $path to $ENVIRONMENT"
        
          # Initialize the values file argument as empty
          helm_args=""

          # Direct values.yaml file exists in chart root
          if [ -f "$path/values.yaml" ]; then
            helm_args="--values $path/values.yaml"
          # Environment-specific values file exists in subfolder
          elif [ -f "$path/values/$ENVIRONMENT.yaml" ]; then
            helm_args="--values $path/values/$ENVIRONMENT.yaml"
          fi
        
          helm upgrade --install \
            --set revision=${{ steps.branch.outputs.revision }} \
            --wait \
            "$(basename "$path")" \
            "$path" \
            $helm_args
        done
