name: Deploy Home Cluster

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible sshpass

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
        env:
          PROXMOX_API_URL: ${{ secrets.PROXMOX_API_URL }}
          PROXMOX_USER: ${{ secrets.PROXMOX_USER }}
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}