# Ansible Inventory - Generated by Terraform
# DO NOT EDIT MANUALLY - This file is auto-generated

[k8s_masters_dev]
%{ for name, vm in k8s_masters_dev ~}
${vm.name} ansible_host=${vm.ip} ansible_user=${vm.user}
%{ endfor ~}

[k8s_workers_dev]
%{ for name, vm in k8s_workers_dev ~}
${vm.name} ansible_host=${vm.ip} ansible_user=${vm.user}
%{ endfor ~}

[k8s_masters_prod]
%{ for name, vm in k8s_masters_prod ~}
${vm.name} ansible_host=${vm.ip} ansible_user=${vm.user}
%{ endfor ~}

[k8s_workers_prod]
%{ for name, vm in k8s_workers_prod ~}
${vm.name} ansible_host=${vm.ip} ansible_user=${vm.user}
%{ endfor ~}

[github_runners_dev]
%{ for name, vm in github_runners_dev ~}
${vm.name} ansible_host=${vm.ip} ansible_user=${vm.user}
%{ endfor ~}

[github_runners_prod]
%{ for name, vm in github_runners_prod ~}
${vm.name} ansible_host=${vm.ip} ansible_user=${vm.user}
%{ endfor ~}

# Aggregate groups for easier targeting
[k8s_masters:children]
k8s_masters_dev
k8s_masters_prod

[k8s_workers:children]
k8s_workers_dev
k8s_workers_prod

[k8s_all:children]
k8s_masters
k8s_workers

[github_runners:children]
github_runners_dev
github_runners_prod

[dev:children]
k8s_masters_dev
k8s_workers_dev
github_runners_dev

[prod:children]
k8s_masters_prod
k8s_workers_prod
github_runners_prod

